version: '3.8'

services:
  # Backend API Service
  esg-api:
    build: .
    container_name: esg-scoring-api
    ports:
      - "8000:8000"  # Export port 8000 ra ngoài
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Frontend UI Service
  esg-ui:
    build: .
    container_name: esg-scoring-ui
    ports:
      - "8501:8501"  # Export port 8501 ra ngoài
    environment:
      - PYTHONPATH=/app
    command: ["streamlit", "run", "src/UI/demo_streamlit_new_api_fixed.py", "--server.address", "0.0.0.0", "--server.port", "8501", "--server.headless", "true"]
    depends_on:
      - esg-api
    restart: unless-stopped

networks:
  default:
    name: esg-network
