services:
  # Backend API Service
  esg-api:
    build: .
    container_name: esg-scoring-api
    ports:
      - "8000:8000"  # Export port 8000 ra ngoài
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
          cpus: "0.75"
          memory: "1.5g"
        limits:
          cpus: "1"
          memory: "3g"
            
  esg-ui:
    build: .
    container_name: esg-scoring-ui
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - API_BASE_URL=http://esg-api:8000
    command: ["streamlit", "run", "src/UI/demo_streamlit_new_api_fixed.py", "--server.address", "0.0.0.0", "--server.port", "8501", "--server.headless", "true"]
    depends_on:
      - esg-api
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: "500m"
        limits:
            cpus: "1"
            memory: "1g"
    restart: unless-stopped

networks:
  default:
    name: esg-network
