from transformers import AutoModelForSequenceClassification, AutoTokenizer

# Load model từ Hub (không cần download lại GTE backbone)
model = AutoModelForSequenceClassification.from_pretrained("chungpt2123/test1", 
                                  trust_remote_code=True,
                                  cache_dir="models")
tokenizer = AutoTokenizer.from_pretrained("Alibaba-NLP/gte-multilingual-base")

# Sử dụng
text = "The company has implemented renewable energy solutions to reduce carbon emissions."
inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=4096)

# Predict ESG và sub-factor
esg_factor, sub_factor = model.predict(inputs.input_ids, inputs.attention_mask)
print(f"ESG Factor: {esg_factor}")
print(f"Sub-factor: {sub_factor}")

texts = [
    "Thực hiện chiến lược phát triển bền vững, Tập đoàn đã và đang thực hiện lộ trình tham gia REDD+ (Chương trình quốc gia về giảm phát thải khí nhà kính thông qua hạn chế mất, suy thoái rừng, nâng cao trữ lượng các-bon và quản lý bền vững tài nguyên rừng) và tiến tới được cấp chứng chỉ rừng bền vững trên toàn bộ diện tích cao su VRG đang quản lý. Sự phát triển của các dự án không được làm thay đổi thảm thực vật trên các con sông và dòng suối lớn để đảm bảo dòng chảy của nước không cạn kiệt. Các hoạt động kinh tế của con người phải đảm bảo không gây ô nhiễm nguồn nước. Cân bằng môi trường sinh thái, bảo vệ các loài thực vật, động vật được bảo tồn trong vùng dự án, thực hiện các biện pháp làm phong phú các loài động thực vật quý hiếm hoặc có nguy cơ tuyệt chủng. Tập đoàn luôn chú trọng đến việc cắt giảm phát thải, sử dụng công nghệ sản xuất sạch, không gây ô nhiễm môi trường, không xâm lấn rừng, không gây tác động làm suy thoái rừng, không khai thác trái phép các sản phẩm từ rừng; quản lý rừng cao su theo hướng bền vững, tăng cường trữ lượng cacbon và đa dạng sinh học, góp phần phát triển rừng. Giảm dần mức tiêu phí năng lượng, tiếp tục có giải pháp tiết kiệm nhiên liệu điện, nước và không sử dụng hóa chất, cải thiện các chỉ tiêu chất lượng, ổn định chất lượng và có thể chủ động kiểm soát các thông số theo yêu cầu của khách hàng, tăng cường sử dụng năng lượng mặt trời đối với các nhà máy chế biến mủ cao su và các nhà máy có điều kiện ứng dụng năng lượng sạch khác. Thực hiện giảm thiểu, tái chế, tái sử dụng chất thải. Cải tiến quy trình quản lý, ứng dụng và chuyển sang các công tiên tiến. Tăng cường sử dụng các nguyên vật liệu, năng lượng tái tạo, sản phẩm thân thiện môi trường. Kiểm soát đánh đông giảm nồng độ ô nhiễm trong nguồn thải bằng điều chỉnh pH và thời gian để mủ đông tụ hoàn toàn. Sử dụng lưới chắn nhiều lớp, vớt mủ thường xuyên từ nguồn phát sinh đến đầu vào hệ thống xử lý nước thải. Tận dụng hồ chứa nước thải, bể gạn để mủ trong nước thải có đủ thời gian đông tụ tự nhiên trước khi chế biến làm tăng các chỉ số Po, PRI và Mooney. Giảm sử dụng hóa chất chất trong xử lý nước thải giúp công ty tiết giảm chi phí và góp phần bảo vệ môi trường.\nViệc ứng dụng công nghệ xử lý nước thải cao su thiên nhiên bằng phương pháp sinh học không sử dụng hóa chất và tái sử dụng nước thải cho sản xuất sau khi xử lý. Tập đoàn chủ động nghiên cứu giải pháp công nghệ chế biến mủ cao su và đã xây dựng được quy trình sản xuất cao su SVR 10, SVR 20 rút gọn không sử dụng hóa chất, với những ưu điểm: tiết giảm suất đầu tư dây chuyền chế biến mủ cao su 30%; tiết kiệm nguyên vật liệu, hóa chất trong sản xuất: dầu DO giảm 12,5%; tiêu thụ điện giảm 30%; tiết kiệm nước 20% so với công nghệ trước đây.\n",
    "Phát triển nông nghiệp ứng dụng công nghệ cao cũng là một định hướng phát triển chiến lược của VRG nhằm tận dụng nguồn đất dồi dào, tăng hiệu quả sử dụng đất. VRG đã và đang chuyển một số diện tích đất trồng cao su có điều kiện phù hợp, thuận tiện giao thông, gần nguồn nước sang sản xuất sản phẩm nông nghiệp công nghệ cao. Đến 2018, Tập đoàn đã thí điểm chuyển đổi gần 200 ha trồng chuối nuôi cấy mô tại Cao su Dầu Tiếng, Đồng Phú và Phước Hòa bước đầu đã khẳng định hiệu quả.\n\nNhững năm qua, VRG chú trọng áp dụng các tiến bộ khoa học kỹ thuật nhằm tăng năng suất vườn cây kinh doanh. Vườn cây kiến thiết cơ bản đạt và vượt tiêu chuẩn, độ đồng đều cao, sinh trưởng nhanh và rút ngắn thời gian kiến thiết cơ bản trên 1 năm. Mỗi năm VRG chế biến trên 350.000 tấn mủ cao su. Bên cạnh đó, Tập đoàn còn cung cấp các chủng loại cao su giống và cây non, cũng như các phương pháp kỹ thuật canh tác cao su nhằm hỗ trợ cho nông dân. \nNông nghiệp ứng dụng công nghệ cao: tuy chưa đóng góp nhiều cho kết quả sản xuất kinh doanh toàn Tập đoàn, tuy nhiên đây là một trong những ngành mũi nhọn có nhiều lợi thế thế từ quỹ đất nông nghiệp sẳn có. Đến 2018, Tập đoàn đã thí điểm chuyển đổi gần 200 hecta trồng chuối cấy mô, bước đầu khẳng định hiệu quả và có kết quả khá khả quan, làm cơ sở tiếp tục phát triển trong các năm tiếp theo. Hiện nay, dù là nước Nông nghiệp nhưng một số sản phẩm trồng trọt vẫn phải nhập khẩu với số lượng lớn, vấn đề an toàn thực phẩm chưa tốt nên chưa đáp ứng được nhu cầu tiêu dùng ngày càng tăng ở trong nước và mở rộng thị trường xuất khẩu...nguyên nhân chính là (1) diện tích đất nông nghiệp manh mún nên không đủ điều kiện để có thể áp dụng các biện pháp kỹ thuật để tăng năng suất, hạ giá thành (2) Thiếu vốn để nhận chuyển giao kỹ thuật, đầu tư phát triển công nghệ cao (3) tâm lý sản xuất nhỏ lẻ còn phổ biến.... Tập đoàn với lợi thế là quản lý quỹ đất lớn, ở nhiều vùng sinh thái phù hợp với nhiều loại cây trồng khác nhau, đủ khả năng huy động nguồn vốn đầu tư, có lực lượng cán bộ kỹ thuật và công nhân có kinh nghiệm trong việc sản xuất lớn và quản lý sản xuất theo quy trình. Đây là một thế mạnh của Tập đoàn khi tham gia phát triển ngành sản xuất này. "
]

for text in texts:
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=4096)
    esg_factor, sub_factor = model.predict(inputs.input_ids, inputs.attention_mask)
    print(f"Text: {text[:50]}...")
    print(f"ESG: {esg_factor}, Sub: {sub_factor}\n")
